import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
DARK_BG = colors.HexColor("#0d1117")
CARD_BG = colors.HexColor("#161b22")
GREEN = colors.HexColor("#00e5a0")
CYAN = colors.HexColor("#00cfff")
RED = colors.HexColor("#ff4757")
ORANGE = colors.HexColor("#ffa502")
PURPLE = colors.HexColor("#7c3aed")
MUTED = colors.HexColor("#8899aa")
WHITE = colors.HexColor("#e2e8f0")
HEADER_BG = colors.HexColor("#0f1923")
ROW_ALT = colors.HexColor("#111827")
BORDER_COLOR = colors.HexColor("#1e2d3d")
def _get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="CG_Title",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=WHITE,
        alignment=TA_CENTER,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="CG_Subtitle",
        fontName="Helvetica",
        fontSize=11,
        textColor=MUTED,
        alignment=TA_CENTER,
        spaceAfter=16,
    ))
    styles.add(ParagraphStyle(
        name="CG_SectionTitle",
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=GREEN,
        spaceBefore=14,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="CG_Body",
        fontName="Helvetica",
        fontSize=10,
        textColor=WHITE,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        name="CG_Small",
        fontName="Helvetica",
        fontSize=8,
        textColor=MUTED,
    ))
    styles.add(ParagraphStyle(
        name="CG_Footer",
        fontName="Helvetica",
        fontSize=7,
        textColor=MUTED,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="CG_RiskHigh",
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=RED,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="CG_RiskMedium",
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=ORANGE,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="CG_RiskLow",
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=GREEN,
        alignment=TA_CENTER,
    ))
    return styles
def _build_header(styles, report_title, report_subtitle=""):
    elements = []
    elements.append(Spacer(1, 10))
    elements.append(Paragraph("🛡️  CyberGuard Pro", styles["CG_Title"]))
    elements.append(Paragraph("Unified Cybersecurity Suite — Report", styles["CG_Subtitle"]))
    elements.append(HRFlowable(
        width="100%", thickness=1, color=GREEN,
        spaceAfter=8, spaceBefore=4,
    ))
    elements.append(Paragraph(report_title, styles["CG_SectionTitle"]))
    if report_subtitle:
        elements.append(Paragraph(report_subtitle, styles["CG_Small"]))
    elements.append(Spacer(1, 6))
    return elements
def _build_footer(styles):
    elements = []
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(
        width="100%", thickness=0.5, color=BORDER_COLOR,
        spaceAfter=8, spaceBefore=8,
    ))
    elements.append(Paragraph(
        f"Generated by CyberGuard Pro · {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} · "
        "For authorized security testing only",
        styles["CG_Footer"],
    ))
    elements.append(Paragraph(
        "⚠ DISCLAIMER: This report is for authorized use only. Unauthorized scanning or testing of systems you do not own is illegal.",
        styles["CG_Footer"],
    ))
    return elements
def _make_table(data, col_widths=None):
    if not data:
        return Spacer(1, 1)
    table = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), GREEN),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("TEXTCOLOR", (0, 1), (-1, -1), WHITE),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8.5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
        else:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), CARD_BG))
    table.setStyle(TableStyle(style_cmds))
    return table
def _severity_text(sev):
    color_map = {"HIGH": "#ff4757", "MEDIUM": "#ffa502", "LOW": "#00e5a0"}
    c = color_map.get(sev, "#8899aa")
    return f'<font color="{c}"><b>{sev}</b></font>'
def _build_pdf(elements):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
    )
    def _on_page(canvas, doc_obj):
        canvas.saveState()
        canvas.setFillColor(DARK_BG)
        canvas.rect(0, 0, A4[0], A4[1], fill=1, stroke=0)
        canvas.restoreState()
    doc.build(elements, onFirstPage=_on_page, onLaterPages=_on_page)
    buf.seek(0)
    return buf.getvalue()
def generate_integrity_report(data: dict) -> bytes:
    styles = _get_styles()
    elements = []
    report_type = data.get("report_type", "hash")
    if report_type == "hash":
        elements += _build_header(styles, "File Hash Report",
                                  f"File: {data.get('filename', 'N/A')}")
        elements.append(Paragraph(
            f"<b>File:</b> {data.get('filename', 'N/A')} &nbsp;&nbsp; "
            f"<b>Size:</b> {data.get('size_bytes', 0):,} bytes &nbsp;&nbsp; "
            f"<b>Timestamp:</b> {data.get('timestamp', 'N/A')}",
            styles["CG_Body"],
        ))
        elements.append(Spacer(1, 12))
        table_data = [["Algorithm", "Hash Value"]]
        for algo in ["md5", "sha1", "sha256", "sha512"]:
            table_data.append([algo.upper(), data.get(algo, "N/A")])
        elements.append(_make_table(table_data, col_widths=[80, 390]))
    elif report_type == "check":
        status = data.get("status", "UNKNOWN")
        elements += _build_header(styles, "File Integrity Check Report",
                                  f"File: {data.get('filename', 'N/A')}")
        if data.get("intact"):
            elements.append(Paragraph("✅ FILE IS INTACT — No modifications detected", styles["CG_RiskLow"]))
        else:
            elements.append(Paragraph(
                f"⚠️ FILE HAS BEEN MODIFIED — {len(data.get('changes', []))} hash(es) changed",
                styles["CG_RiskHigh"],
            ))
        elements.append(Spacer(1, 12))
        elements.append(Paragraph("Current File Hashes", styles["CG_SectionTitle"]))
        table_data = [["Algorithm", "Hash Value", "Status"]]
        current = data.get("current_hashes", {})
        changed_algos = {c["algo"] for c in data.get("changes", [])}
        for algo in ["md5", "sha1", "sha256", "sha512"]:
            status_text = "CHANGED" if algo in changed_algos else "OK"
            table_data.append([algo.upper(), current.get(algo, "N/A"), status_text])
        elements.append(_make_table(table_data, col_widths=[70, 340, 60]))
        if data.get("baseline_hashes"):
            elements.append(Spacer(1, 8))
            elements.append(Paragraph("Baseline (Original) Hashes", styles["CG_SectionTitle"]))
            baseline = data["baseline_hashes"]
            bl_data = [["Algorithm", "Hash Value"]]
            for algo in ["md5", "sha1", "sha256", "sha512"]:
                bl_data.append([algo.upper(), baseline.get(algo, "N/A")])
            elements.append(_make_table(bl_data, col_widths=[80, 390]))
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(
            f"<b>Checked at:</b> {data.get('checked_at', 'N/A')} &nbsp;&nbsp; "
            f"<b>Baseline saved at:</b> {data.get('baseline_saved_at', 'N/A')}",
            styles["CG_Small"],
        ))
    elements += _build_footer(styles)
    return _build_pdf(elements)
def generate_scan_report(data: dict) -> bytes:
    styles = _get_styles()
    elements = []
    elements += _build_header(styles, "Web Vulnerability Scan Report",
                              f"Target: {data.get('url', 'N/A')}")
    risk = data.get("risk", "LOW")
    risk_style = {"HIGH": "CG_RiskHigh", "MEDIUM": "CG_RiskMedium"}.get(risk, "CG_RiskLow")
    elements.append(Paragraph(f"Overall Risk: {risk}", styles[risk_style]))
    elements.append(Spacer(1, 6))
    summary = data.get("summary", {})
    elements.append(Paragraph(
        f"<b>Total Issues:</b> {summary.get('total', 0)} &nbsp;&nbsp; "
        f"<b>High:</b> {summary.get('high', 0)} &nbsp;&nbsp; "
        f"<b>Medium:</b> {summary.get('medium', 0)} &nbsp;&nbsp; "
        f"<b>Missing Headers:</b> {summary.get('missing_headers', 0)} &nbsp;&nbsp; "
        f"<b>Scan Time:</b> {data.get('scan_time', 'N/A')}",
        styles["CG_Body"],
    ))
    elements.append(Spacer(1, 10))
    info = data.get("info", [])
    if info:
        elements.append(Paragraph("Page Information", styles["CG_SectionTitle"]))
        for line in info:
            elements.append(Paragraph(f"• {line}", styles["CG_Body"]))
        elements.append(Spacer(1, 8))
    vulns = data.get("vulnerabilities", [])
    elements.append(Paragraph("Vulnerabilities Found", styles["CG_SectionTitle"]))
    if vulns:
        vuln_data = [["Type", "Severity", "Details"]]
        for v in vulns:
            details = v.get("form") or v.get("path") or ""
            if v.get("payload"):
                details += f" | payload: {v['payload']}"
            if v.get("evidence"):
                details += f" | evidence: {v['evidence']}"
            vuln_data.append([v.get("type", ""), v.get("severity", ""), details[:80]])
        elements.append(_make_table(vuln_data, col_widths=[130, 60, 280]))
    else:
        elements.append(Paragraph("✅ No direct vulnerabilities detected.", styles["CG_Body"]))
    elements.append(Spacer(1, 8))
    headers = data.get("headers", {})
    missing = headers.get("missing", [])
    present = headers.get("present", [])
    if missing:
        elements.append(Paragraph("Missing Security Headers", styles["CG_SectionTitle"]))
        hdr_data = [["Header", "Status"]]
        for h in missing:
            hdr_data.append([h["header"], "MISSING"])
        elements.append(_make_table(hdr_data, col_widths=[250, 220]))
        elements.append(Spacer(1, 6))
    if present:
        elements.append(Paragraph("Present Security Headers", styles["CG_SectionTitle"]))
        hdr_data = [["Header", "Value"]]
        for h in present:
            hdr_data.append([h["header"], h.get("value", "")[:60]])
        elements.append(_make_table(hdr_data, col_widths=[180, 290]))
        elements.append(Spacer(1, 6))
    ssl_info = data.get("ssl", {})
    elements.append(Paragraph("SSL / TLS Information", styles["CG_SectionTitle"]))
    ssl_status = "✅ HTTPS Enabled" if ssl_info.get("has_ssl") else "❌ HTTP Only (No SSL)"
    elements.append(Paragraph(ssl_status, styles["CG_Body"]))
    if ssl_info.get("version"):
        elements.append(Paragraph(f"Version: {ssl_info['version']}", styles["CG_Small"]))
    if ssl_info.get("cipher"):
        elements.append(Paragraph(f"Cipher: {ssl_info['cipher']}", styles["CG_Small"]))
    for issue in ssl_info.get("issues", []):
        elements.append(Paragraph(f"⚠ {issue}", styles["CG_Small"]))
    elements += _build_footer(styles)
    return _build_pdf(elements)
def generate_recon_report(data: dict) -> bytes:
    styles = _get_styles()
    elements = []
    elements += _build_header(styles, "Network Reconnaissance Report",
                              f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    sections = data.get("sections", [])
    for section in sections:
        sec_type = section.get("type", "")
        sec_data = section.get("data", {})
        if sec_type == "portscan":
            elements.append(Paragraph("Port Scan Results", styles["CG_SectionTitle"]))
            elements.append(Paragraph(
                f"<b>Host:</b> {sec_data.get('host', 'N/A')} &nbsp;&nbsp; "
                f"<b>IP:</b> {sec_data.get('ip', 'N/A')} &nbsp;&nbsp; "
                f"<b>Ports Scanned:</b> {sec_data.get('ports_scanned', 0)} &nbsp;&nbsp; "
                f"<b>Duration:</b> {sec_data.get('duration_s', 0)}s",
                styles["CG_Body"],
            ))
            elements.append(Spacer(1, 6))
            open_ports = sec_data.get("open_ports", [])
            if open_ports:
                port_data = [["Port", "Service", "State", "Banner"]]
                for p in open_ports:
                    port_data.append([
                        str(p["port"]), p.get("service", "unknown"),
                        p.get("state", "open"), (p.get("banner", "") or "")[:50],
                    ])
                elements.append(_make_table(port_data, col_widths=[60, 80, 60, 270]))
            else:
                elements.append(Paragraph("No open ports found.", styles["CG_Body"]))
            elements.append(Spacer(1, 10))
        elif sec_type == "dns":
            elements.append(Paragraph("DNS Lookup Results", styles["CG_SectionTitle"]))
            elements.append(Paragraph(
                f"<b>Domain:</b> {sec_data.get('domain', 'N/A')}",
                styles["CG_Body"],
            ))
            records = sec_data.get("records", {})
            if records:
                dns_data = [["Record Type", "Value"]]
                for rtype, val in records.items():
                    dns_data.append([rtype, str(val)])
                elements.append(_make_table(dns_data, col_widths=[100, 370]))
            all_ips = sec_data.get("all_ips", [])
            if all_ips:
                elements.append(Spacer(1, 4))
                elements.append(Paragraph(
                    f"<b>All IPs:</b> {', '.join(all_ips)}",
                    styles["CG_Small"],
                ))
            elements.append(Spacer(1, 10))
        elif sec_type == "ping":
            elements.append(Paragraph("Ping / Reachability Results", styles["CG_SectionTitle"]))
            if sec_data.get("reachable"):
                elements.append(Paragraph(
                    f"✅ <b>REACHABLE</b> — Host: {sec_data.get('host', 'N/A')} "
                    f"| IP: {sec_data.get('ip', 'N/A')} "
                    f"| Latency: {sec_data.get('latency_ms', 'N/A')} ms",
                    styles["CG_Body"],
                ))
            else:
                elements.append(Paragraph(
                    f"❌ <b>UNREACHABLE</b> — Host: {sec_data.get('host', 'N/A')} "
                    f"| Error: {sec_data.get('error', 'N/A')}",
                    styles["CG_Body"],
                ))
            elements.append(Spacer(1, 10))
        elif sec_type == "subdomains":
            elements.append(Paragraph("Subdomain Enumeration Results", styles["CG_SectionTitle"]))
            elements.append(Paragraph(
                f"<b>Domain:</b> {sec_data.get('domain', 'N/A')} &nbsp;&nbsp; "
                f"<b>Found:</b> {sec_data.get('total', 0)} subdomains",
                styles["CG_Body"],
            ))
            found = sec_data.get("found", [])
            if found:
                sub_data = [["Subdomain", "IP Address"]]
                for s in found:
                    sub_data.append([s["subdomain"], s["ip"]])
                elements.append(_make_table(sub_data, col_widths=[250, 220]))
            elements.append(Spacer(1, 10))
        elif sec_type == "geoip":
            elements.append(Paragraph("IP Geolocation Results", styles["CG_SectionTitle"]))
            geo_data = [["Field", "Value"]]
            for field in ["target", "ip", "country", "city", "isp", "lat", "lon"]:
                val = sec_data.get(field, "N/A")
                geo_data.append([field.capitalize(), str(val)])
            elements.append(_make_table(geo_data, col_widths=[120, 350]))
            elements.append(Spacer(1, 10))
    if not sections:
        elements.append(Paragraph("No reconnaissance data provided.", styles["CG_Body"]))
    elements += _build_footer(styles)
    return _build_pdf(elements)
def generate_encryption_report(data: dict) -> bytes:
    styles = _get_styles()
    elements = []
    operation = data.get("operation", "encrypt").capitalize()
    elements += _build_header(styles, f"File {operation}ion Report",
                              f"File: {data.get('filename', 'N/A')}")
    status = data.get("status", "success")
    if status == "success":
        elements.append(Paragraph(f"✅ {operation}ion completed successfully", styles["CG_RiskLow"]))
    else:
        elements.append(Paragraph(f"❌ {operation}ion failed", styles["CG_RiskHigh"]))
    elements.append(Spacer(1, 12))
    table_data = [["Property", "Value"]]
    details = [
        ("Operation", operation + "ion"),
        ("Input File", data.get("filename", "N/A")),
        ("Output File", data.get("output_filename", "N/A")),
        ("Algorithm", data.get("algorithm", "AES-256-CBC")),
        ("Key Derivation", data.get("kdf", "PBKDF2-HMAC-SHA256")),
        ("Iterations", str(data.get("iterations", "120,000"))),
        ("Key Size", data.get("key_size", "256 bits")),
        ("Timestamp", data.get("timestamp", datetime.now().isoformat())),
    ]
    for label, val in details:
        table_data.append([label, val])
    elements.append(_make_table(table_data, col_widths=[150, 320]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("Encryption Process", styles["CG_SectionTitle"]))
    process_data = [
        ["Step", "Description"],
        ["1. Key Derivation", "Password → PBKDF2-HMAC-SHA256 (120k iterations) → 256-bit key"],
        ["2. Random Salt", "16-byte cryptographic random salt generated per file"],
        ["3. Random IV", "16-byte random initialization vector (no determinism)"],
        ["4. AES-256-CBC", "Plaintext padded (PKCS7) then encrypted with AES-256 in CBC mode"],
        ["5. Output Format", "MAGIC(9B) + SALT(16B) + IV(16B) + CIPHERTEXT"],
    ]
    elements.append(_make_table(process_data, col_widths=[120, 350]))
    elements += _build_footer(styles)
    return _build_pdf(elements)
